project:
  type: website
  output-dir: docs

website:
  title: "MATH 012: R-Labs"
  search: true
  reader-mode: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Lab_1.qmd
        text: Lab 1
      - href: Lab_2.qmd       # <--- I added this link for you
        text: Lab 2           # <--- This is the button text
      - href: Lab_3.qmd       # <--- I added this link for you
        text: Lab 3           # <--- This is the button text
  favicon: lehigh-icon.ico
  sidebar:
    - style: "floating"
      contents:
        - section: "Lab Sessions"
          contents:
            - Lab_1.qmd
            - Lab_2.qmd       # <--- I added this to the sidebar
            - Lab_3.qmd

filters:
  - webr

format:
  html:
    toc: true
    css: styles.css
    theme: sketchy
    embed-resources: true     # <--- Keeps the output easy to manage

editor: visual
